default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost 
  username: postgres 
  password: 11111 

development:
  <<: *default
  database: lumber_app_development

test:
  <<: *default
  database: lumber_app_test

production:
  <<: *default
  database: lumber_app_production
  username: postgres
  password: <%= ENV["LUMBER_APP_DATABASE_PASSWORD"] %> # Use environment variable for production
